const ActionType = {
	FETCH_BOOKS_REQUEST: 'FETCH_BOOKS_REQUEST',
	FETCH_BOOKS_SUCCESS: 'FETCH_BOOKS_SUCCESS',
	FETCH_BOOKS_FAILURE: 'FETCH_BOOKS_FAILURE',
	ADD_BOOK_TO_CART: 'ADD_BOOK_TO_CART',
	DECREASE_COUNT: 'DECREASE_COUNT',
	REMOVE_BOOK_FROM_CART: 'REMOVE_BOOK_FROM_CART',
};

export {ActionType};
